---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: monitoring-edit
  namespace: "{{ .Values.newProject.name }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: monitoring-edit
subjects:
{{- if .Values.newProject.groups }}
{{- if .Values.newProject.groups.admin }}
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: "{{ .Values.newProject.groups.admin }}"
{{- else}}
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: "{{ .Values.newProject.name }}-admin"
{{- end}}
{{- if .Values.newProject.groups.edit }}
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: "{{ .Values.newProject.groups.edit }}"
{{- else}}
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: "{{ .Values.newProject.name }}-edit"
{{- end}}
{{- else}}
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: "{{ .Values.newProject.name }}-admin"
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: "{{ .Values.newProject.name }}-edit"
{{- end}}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: monitoring-rules-view
  namespace: "{{ .Values.newProject.name }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: monitoring-rules-view
subjects:
{{- if .Values.newProject.groups }}
{{- if .Values.newProject.groups.admin }}
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: "{{ .Values.newProject.groups.admin }}"
{{- else}}
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: "{{ .Values.newProject.name }}-admin"
{{- end}}
{{- if .Values.newProject.groups.edit }}
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: "{{ .Values.newProject.groups.edit }}"
{{- else}}
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: "{{ .Values.newProject.name }}-edit"
{{- end}}
{{- if .Values.newProject.groups.view }}
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: "{{ .Values.newProject.groups.view }}"
{{- else}}
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: "{{ .Values.newProject.name }}-view"
{{- end}}
{{- else}}
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: "{{ .Values.newProject.name }}-admin"
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: "{{ .Values.newProject.name }}-edit"
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: "{{ .Values.newProject.name }}-view"
{{- end}}
