---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: view
  namespace: "{{ .Values.newProject.name }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "view"
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
{{- if .Values.newProject.groups }}
{{- if .Values.newProject.groups.view }}
  name: "{{ .Values.newProject.groups.view }}"
{{- else}}
  name: "{{ .Values.newProject.name }}-view"
{{- end}}
{{- else}}
  name: "{{ .Values.newProject.name }}-view"
{{- end}}
