kind: Secret
apiVersion: v1
type: kubernetes.io/dockerconfigjson
metadata:
  name: docker-io
  namespace: "{{ .Values.newProject.name }}"
  labels:
    {{- include "project-request.labels" . | nindent 4 }}
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXItaW8iOnsidXNlcm5hbWUiOiJrbGVua2VzNzQiLCJwYXNzd29yZCI6Im5iWmM1dVRuelRwUlZaWSIsImVtYWlsIjoia2xlbmtlczc0QGdtYWlsLmNvbSIsImF1dGgiOiJhMnhsYm10bGN6YzBPbTVpV21NMWRWUnVlbFJ3VWxaYVdRPT0ifX19
